Cocina-Tech/Controllers/RegistroPro/RegistroPlatilloController.cs
using Cocina_Tech.BO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cocina_Tech.Models;
using System.Data;
using System.IO;

namespace Cocina_Tech.Controllers.RegistroPro
{
    public class RegistroPlatilloController : Controller
    {
        PlatilloModel ObjModel = new PlatilloModel();

        CategoriaModel Objcat = new CategoriaModel();
        Registro objUsu = new Registro();
        // GET: RegistroPlatillo
        public ActionResult RegistroPlatillo()
        {
            return View(ObjModel.TABLA_PLATILLO().Tables[0]);
        }
        public ActionResult RegistroUsuarios()
        {
            return View(objUsu.Tabla_Usuario().Tables[0]);
        }


        public ActionResult EliminarUsu(string ID)
        {
            try
            {
                UsuarioBO objBO = new UsuarioBO();
                objBO.ID = int.Parse(ID);
                objBO.estado = false;
                objUsu.EliminarUsuario(objBO);
                RegistroUsuarios();
               
            }
            catch { }
            return View("RegistroUsuarios");
        }


        public ActionResult WebAdministrador()
        {
            return View();
        }
        public ActionResult Pedidos()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AgregarPlatillo(HttpPostedFileBase algo, string Nombre, string TiempoPreparacion, string IDC, HttpPostedFileBase Portada, string Precio /*HttpPostedFileBase[] Imagen*/)
        {
            PlatilloBO ObjBO = new PlatilloBO();
            CategoriaBO objC = new CategoriaBO();
            Galeria obJGa = new Galeria();
            ObjBO.Nombre = Nombre;


            if (algo != null && algo.ContentLength > 0)
            {
                string namefile = algo.FileName;
                ObjBO.Recetario = new byte[algo.ContentLength];
                algo.InputStream.Read(ObjBO.Recetario, 0, algo.ContentLength);
            }
            ObjBO.TiempoPreparacion = TiempoPreparacion;
            ObjBO.FechaCreacion = DateTime.Now;
            ObjBO.IDC = int.Parse(IDC);
            ObjBO.Estado = true;
            if (Portada != null && Portada.ContentLength > 0)
            {
                string imgfile = Portada.FileName;
                ObjBO.Portada = new byte[Portada.ContentLength];
                Portada.InputStream.Read(ObjBO.Portada, 0, Portada.ContentLength);
            }
            ObjBO.Precio = Precio;

            ObjBO.IDUSUARIO = int.Parse(Session["Usuario"].ToString());
            //if (Imagen != null && Imagen.Length > 0)
            //{
            //    for (int i = 0; i < Imagen.Length; i++)
            //    {
            //        string imgfile = Imagen[i].FileName;
            //        obJGa.Imagen = new byte[Imagen[i].ContentLength];
            //        Imagen[i].InputStream.Read(obJGa.Imagen, 0, Imagen[i].ContentLength);
            //    }

            //}
            //obJGa.Estado = true;
            //obJGa.Fecha = DateTime.Now;
            //obJGa.Id_platillo =
            ObjModel.AgregarPlatillo(ObjBO);
            //ObjModel.AgregarGaleria(obJGa);


            return RedirectToAction("RegistroPlatillo");
        }     


       
        [ChildActionOnly]
        public ActionResult ParcialPlatillo()
        {
            var cat = new PlatilloBO();
            cat.Categorias = ObjModel.listaCat();
            return PartialView("ParcialPlatillo", cat);
        }

        //[ChildActionOnly]
        public ActionResult MostrarPlatilloParcial()
        {
            return PartialView(ObjModel.Recuperar());
        }

        public ActionResult MostrarPlatillo()
        {
            return View(ObjModel.Recuperar());
        }
        
        public ActionResult RegistarCategorias()
        {
            return View(Objcat.Tabla_Categoria_bd());
        }

        public ActionResult Agregar(string Nombre)
        {
            CategoriaBO ObjBO = new CategoriaBO();
            ObjBO.Nombre = Nombre;
            ObjBO.FechaCreacion = DateTime.Now;
            ObjBO.Estado = true;
            Objcat.Agregar(ObjBO);
            RegistarCategorias();
            return RedirectToAction("RegistarCategorias");
        }

        public ActionResult Eliminarcat(string ID)
        {
            CategoriaBO objBO = new CategoriaBO();
            objBO.IDCT = int.Parse(ID);
            objBO.Estado = false;
            Objcat.EliminarCat(objBO);
            RegistarCategorias();
            return View("RegistarCategorias");
        }

     


        public ActionResult IngredienteM()
        {
            return View(Objcat.Tabla_Medida().Tables[0]);
        }


        public ActionResult AgregarMedida(string Medida)//ingresa medida
        {
            IngredienteM ObjBO = new BO.IngredienteM();
            ObjBO.Medida = Medida;
            ObjBO.EstadoM =true ;
            Objcat.AgregarMedida(ObjBO);
            return RedirectToAction("IngredienteM");
        }

        
        public ActionResult VistaIngrediente()
        {
            return View(Objcat.Tabla_Ingrediente().Tables[0]);
        }

        public ActionResult Ingrediente(string Nombre, string IDMedida)//Ingresar ingrediente
        {
            IngredientePrin OBJBO = new BO.IngredientePrin();
            IngredienteM ing = new BO.IngredienteM();
            OBJBO.Nombre = Nombre;
            OBJBO.EstadoI = true;
            OBJBO.Feha = DateTime.Now;
            OBJBO.idMedida = int.Parse(IDMedida);
            Objcat.AgregarIngrediente(OBJBO);
            return RedirectToAction("VistaIngrediente");
        }

        public ActionResult EliminarIng(string ID)
        {
           IngredientePrin  objBO = new IngredientePrin();
            objBO.IDIn = int.Parse(ID);
            objBO.EstadoI = false;
            Objcat.EliminarIng(objBO);
            RegistarCategorias();
            return View("RegistarCategorias");
        }


        [ChildActionOnly]
        public ActionResult vistaMedida()
        {
            var medida = new IngredientePrin();
            medida.Medidas = Objcat.listaMedida();
            return PartialView("vistaMedida", medida);
        }


        public ActionResult AgregarChef()
        {
            return View(objUsu.Tabla_Chef().Tables[0]); 
        }

        public ActionResult chefEmpleado(string Nombre, string Apellido, string Telefono, DateTime FechaNac, string Correo, string Usuario, string Contraseña, HttpPostedFileBase Fotografia)
        {
            UsuarioBO ObjBO = new UsuarioBO();
            ObjBO.Nombre = Nombre;
            ObjBO.Apellido = Apellido;
            ObjBO.Telefono = Telefono;
            ObjBO.FechaNac = FechaNac;
            ObjBO.Correo = Correo;
            ObjBO.Usuario = Usuario;
            ObjBO.Contraseña = Contraseña;

            if (Fotografia != null && Fotografia.ContentLength > 0)
            {
                string imgP = Fotografia.FileName;
                ObjBO.Fotografia = new byte[Fotografia.ContentLength];
                Fotografia.InputStream.Read(ObjBO.Fotografia, 0, Fotografia.ContentLength);


            }
            ObjBO.estado = true;
            objUsu.AgregarChef(ObjBO);

            return RedirectToAction("AgregarChef");

        }

        public ActionResult EliminarChef(string ID)
        {
            try
            {
                UsuarioBO objBO = new UsuarioBO();
                objBO.ID = int.Parse(ID);
                objBO.estado = false;
                objUsu.EliminarChef(objBO);
                AgregarChef();

            }
            catch { }
            return View("AgregarChef");
        }
        [ChildActionOnly]
        public ActionResult Agregaringredentespatillo ()
        {

            return PartialView();
        }

    }
}

Cocina-Tech/Controllers/ReportesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cocina_Tech.BO;
using Cocina_Tech.Models;
using System.Data;
using System.IO;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;

namespace Cocina_Tech.Controllers
{
    public class ReportesController : Controller
    {
        ConexionModel Con = new ConexionModel();
        ReportesModel ObjDAO = new ReportesModel();
         
        // GET: Reportes
        public ActionResult ReporteUsuario()
        {
            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Reportes/Viewers/"), "ReporteUsuarios.rpt"));

            rd.SetDataSource(ObjDAO.Usuarios());
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/pdf", "UsuariosReporte.pdf");        
        }     
        
        public ActionResult ReporteChef()
        {
            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Reportes/Viewers/"), "ReporteChef.rpt"));

            rd.SetDataSource(ObjDAO.UsuarioChef());
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/pdf", "ChefReporte.pdf");
        } 
        
        public ActionResult ReporteIngrediente()
        {
            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/Reportes/Viewers/"), "ReporteIngrerdientes.rpt"));

            rd.SetDataSource(ObjDAO.Ingredientes());
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/pdf", "IngredienteReporte.pdf");
        }      
    }
}

Cocina-Tech/Views/RegistroPlatillo/ActualizarCat.cshtml
@using System.Data;
@using Cocina_Tech.BO
@Model DataTable;
@{
    ViewBag.Title = "ActualizarCat";
    Layout = "~/Views/Administrador/Administrador.cshtml";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Platillos</h4>
                    </div>


                    <div class="content">

                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label>Nombre De la Categoria de Platillo</label>
                                    <input type="text" class="form-control" placeholder="Platillo" name="Nombre">
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="form-group">
                                    <label>ID</label>
                                    <input type="text" class="form-control" placeholder="Platillo" name="Nombre">
                                </div>
                            </div>


                            <div class="col-md-5">
                                <div class="form-group">
                                    <label>Estado</label>
                                    
                                </div>
                            </div>

                        </div>

                        <input id="Button1" type="submit" value="Agregar Platillo" class="primary-color" />
                        <div class="row">
                            <div class="col-md-12">
                                <div class="panel panel-default">

                                    <div class="panel-body panel-body-table">
                                        <div class="table-responsive">
                                            <table class="table table-bordered table-striped table-actions">
                                                <thead>
                                                    <tr>
                                                        <th width="50">ID</th>
                                                        <th>NOMBRE CATEGORIA</th>
                                                        <th width="100">ESTADO</th>
                                                        <th width="100">FECHA</th>
                                                        <th width="100">actions</th>
                                                    </tr>
                                                </thead>
                                                @foreach (DataRow row in Model.Rows)
                                                {
                                                    <tbody>


                                                        <tr id="trow_1">
                                                            <td class="text-center">@row["ID"]</td>
                                                            <td><strong>@row["NOMBRE"]</strong></td>
                                                            <td><span class="label label-success">@row["ESTADO"]</span></td>
                                                            <td>@row["FECHACREACION"]</td>
                                                            <td>
                                                                <button class="btn btn-default btn-rounded btn-sm"><span class="fa fa-pencil"></span></button>
                                                                <button class="btn btn-danger btn-rounded btn-sm" onClick="delete_row('trow_1');"><span class="fa fa-times"></span></button>
                                                            </td>

                                                    </tbody>
                                                }
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>



                    </div>
                    </div>
            </div>
        </div>
    </div>
</div>

Cocina-Tech/Views/RegistroPlatillo/AgregarChef.cshtml
@using System.Data;
@model DataTable
@{
    ViewBag.Title = "AgregarChef";
    Layout = "~/Views/Administrador/Administrador.cshtml";
}




    <div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                @* @Html.ActionLink("Reporte", "ReporteChef", "Reportes")*@
                <div class="card">
                    <div class="header">
                        <h4 class="title">REGISTRO CHEF</h4>
                    </div>
                    <div class="content">
                        @using (Html.BeginForm("chefEmpleado", "RegistroPlatillo", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <form>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Nombres</label>
                                <input type="text" class="form-control" placeholder="Nombres" name="Nombre">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Apellidos</label>
                                <input type="text" class="form-control" placeholder="Apellidos" name="Apellido">
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Correo</label>
                            <input type="email" class="form-control" placeholder="Email" name="Correo"style="margin-left:-15px">
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Contraseña</label>
                            <input type="text" class="form-control" placeholder="Contraseña" name="Contraseña">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Usuario</label>
                            <input type="text" class="form-control" placeholder="Username" name="Usuario">
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>Fecha De Nacimiento</label>
                                <input type="date" class="form-control" placeholder="" id="FechaNaci" name="FechaNac">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>Telefono</label>
                                <input type="text" class="form-control" placeholder="Telefono" name="Telefono">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Foto De Perfil</label>
                                <input id="File1" type="file" name="Fotografia" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-1">
                        <button type="submit" class="btn btn-info btn-fill pull-right"style="margin-right:-10px">Guardar</button>
                    </div>
                    <div class="clearfix"></div>
                </form>
}
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default">

                                <div class="panel-body panel-body-table">
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-striped table-actions">
                                            <thead>
                                                <tr>
                                                    <th width="50">ID</th>
                                                    <th>NOMBRE CHEF</th>
                                                    <th width="100">APELLIDOS</th>
                                                    <th width="100">TELEFONO</th>
                                                    <th width="100">FECHA DE NACIMIENTO</th>
                                                    <th width="100">CORREO</th>
                                                    <th width="100">USUARIO</th>
                                                    <th width="100">ESTADO</th>
                                                    <th width="100">ACCION</th>

                                                </tr>
                                            </thead>
                                            @foreach (DataRow row in Model.Rows)
                                {
                                    <tbody>


                                        <tr id="trow_1">
                                            <td class="text-center">@row["ID"]</td>
                                            <td><strong>@row["NOMBRE"]</strong></td>
                                            <td><strong>@row["APELLIDOS"]</strong></td>
                                            <td><strong>@row["TELEFONO"]</strong></td>
                                            <td>@row["FECHANACIMIENTO"]</td>
                                            <td><strong>@row["CORREO"]</strong></td>
                                            <td><strong>@row["USUARIO"]</strong></td>
                                            <td><span class="label label-success">@(row["ESTADO"].ToString()=="True" ? "Disponible" : "No Disponible")</span></td>
                                            <td>
                                                <button class="btn btn-default btn-rounded btn-sm"><span class="fa fa-pencil"></span></button>
                                                <button class="btn btn-danger btn-rounded btn-sm" onclick="location.href='@($"/RegistroPlatillo/Eliminarcat/{@row["ID"]}")'">

                                                    <span class="fa fa-times">
                                                        @*@Html.ActionLink("Eliminar", "Eliminarcat", "RegistroPlatillo", new { ID = row["ID"] })*@
                                                    </span>
                                                </button>
                                            </td>

                                    </tbody>
                    }
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>



                </div>
            </div>
            </div>

</div>
</div>

Cocina-Tech/Views/RegistroPlatillo/EstatusCategoria.cshtml
@model Cocina_Tech.BO.CategoriaBO

Cocina-Tech/Views/RegistroPlatillo/ParcialPlatillo.cshtml
@model Cocina_Tech.BO.PlatilloBO

<div class="cold-md-3">

    <div class="form-group">
        <label>Categoria</label>
        @Html.DropDownListFor(x => x.IDC, new SelectList(Model.Categorias, "IDCT", "NOMBRE"), new { @class = "form-control"})
    </div>


</div>

Cocina-Tech/Views/RegistroPlatillo/Pedidos.cshtml
@{
    ViewBag.Title = "Pedidos";
    Layout = "~/Views/Administrador/Administrador.cshtml";
}

Cocina-Tech/Views/RegistroPlatillo/RegistroUsuarios.cshtml
@using System.Data;
@model DataTable
@{
    ViewBag.Title = "RegistroUsuarios";
    Layout = "~/Views/Administrador/Administrador.cshtml";
}

<div class="row">

    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">Registro de Usuarios</h4>
            </div>
            @*@Html.ActionLink("Reporte", "ReporteUsuario", "Reportes")*@

            <div class="panel panel-default">

                <div class="panel-body panel-body-table">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-actions">
                            <thead>
                                <tr>
                                    <th width="50">ID</th>
                                    <th>NOMBRE</th>
                                    <th>APELLIDOS</th>
                                    <th width="100">TELEFONO</th>
                                    <th width="100">FECHANACIMIENTO</th>
                                    <th width="100">CORREO</th>
                                    <th width="100">USUARIO</th>
                                    <th width="100">ESTADO</th>

                                    <th width="100">ACCIONES</th>
                                </tr>
                            </thead>
                            @foreach (DataRow row in Model.Rows)
                    {
                        <tbody>


                            <tr id="trow_1">
                                <td class="text-center">@row["ID"]</td>
                                <td><strong>@row["NOMBRE"]</strong></td>
                                <td><strong>@row["APELLIDOS"]</strong></td>
                                <td>@row["TELEFONO"]</td>
                                <td><strong>@row["FECHANACIMIENTO"]</strong></td>
                                <td><strong>@row["CORREO"]</strong></td>
                                <td><strong>@row["USUARIO"]</strong></td>
                                <td><span class="label label-success">@(row["ESTADO"].ToString()=="True" ? "Disponible" : "No Disponible")</span></td>
                                <td>

                                    <button class="btn btn-danger btn-rounded btn-sm" onclick="location.href='@($"/RegistroPlatillo/EliminarUsu/{@row["ID"]}")'">

                                        <span class="fa fa-times">
                                            @*@Html.ActionLink("Eliminar", "Eliminarcat", "RegistroPlatillo", new { ID = row["ID"] })*@
                                        </span>
                                    </button>
                                </td>

                        </tbody>
            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Cocina-Tech/Views/RegistroPlatillo/VistaIngrediente.cshtml
@{
    ViewBag.Title = "VistaIngrediente";
    Layout = "~/Views/Administrador/Administrador.cshtml";
}
@using System.Data;
@model DataTable


@using (Ajax.BeginForm("Ingrediente", "RegistroPlatillo", new AjaxOptions() { HttpMethod = "POST" }))
{
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">INGREDIENTES</h4>
                        </div>
                        <div class="content">
                            <form>
                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <label>Ingrediente</label>
                                            <input type="text" class="form-control" placeholder="Nombre" name="Nombre">
                                        </div>
                                    </div>                                   
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            @{
                                                Html.RenderAction("vistaMedida", "RegistroPlatillo");
                                            }
                                        </div>
                                    </div>
                                    <div class="col-md-2" style="margin-top:24px">
                                        <button type="submit" class="btn btn-info btn-fill">Guardar</button>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group">
                                            <!--label>Reporte</!--label>-->
                                            @*@Html.ActionLink("Reporte", "ReporteIngrediente", "Reportes")*@
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="panel panel-default">

                                                <div class="panel-body panel-body-table">
                                                    <div class="table-responsive">
                                                        <table class="table table-bordered table-striped table-actions">
                                                            <thead>
                                                                <tr>
                                                                    <th width="50">ID</th>
                                                                    <th>Nombre</th>
                                                                    <th width="100">ESTADO</th>
                                                                    <th>MEDIDA</th>
                                                                    <th>FECHA</th>
                                                                    <th width="50">IDMEDIDA</th>                                                                   
                                                                    <th width="100">ACCION</th>
                                                                </tr>
                                                            </thead>
                                                            @foreach (DataRow row in Model.Rows)
                                                            {
                                                                <tbody>


                                                                    <tr id="trow_1">
                                                                        <td class="text-center">@row["ID"]</td>
                                                                        <td><strong>@row["NOMBRE"]</strong></td>
                                                                        <td><span class="label label-success">@(row["Estado"].ToString()=="True" ? "Disponible" : "No Disponible")</span></td>
                                                                        <td>@row["MEDIDA"]</td>
                                                                        <td>@row["FECHACREACION"]</td>
                                                                        <td>@row["IDMEDIDA"]</td>
                                                                        <td>
                                                                            <button class="btn btn-default btn-rounded btn-sm" onclick="location.href='@($"/RegistroPlatillo/EliminarIng/{@row["ID"]}")'">
                                                                                <span class="fa fa-pencil">
                                                                                </span>
                                                                            </button>


                                                                        </td>

                                                                </tbody>
                                                            }
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                               
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>

                                                }