Cocina-Tech/Controllers/Admin/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cocina_Tech.Models;
using Cocina_Tech.BO;


namespace Cocina_Tech.Controllers.Admin
{
    public class AdministradorController : Controller
    {
        PlatilloModel ObjModel = new PlatilloModel();
        CategoriaModel categoriamodel = new CategoriaModel();
        PlatilloBO platillobo = new PlatilloBO();

        // GET: Administrador
        Registro objusu = new Registro();
        MensajeModel objMen = new MensajeModel();
        public ActionResult Administrador()
        {
            ViewBag.Count = objMen.NumeroMensaje();
            return View();
        }

        public ActionResult Platillopingrediente()
        {
            return View(ObjModel.TABLA_PLATILLO().Tables[0]);
        }

        public ActionResult Platillo(int ID)
        {
            Session["IDPLATILLO"] = ID;
            return View(ObjModel.TABLA_PLATILLOID(ID).Tables[0]);
        }

        [ChildActionOnly]
        public ActionResult Ingredientexplatillo()
        {
            int ID = int.Parse(Session["IDPLATILLO"].ToString());
            return View(ObjModel.Tablaingred(ID));
        }

        [ChildActionOnly]
        public ActionResult Ingredientes()
        {
            return View(categoriamodel.Tabla_Ingrediente().Tables[0]);
        }

        [ChildActionOnly]
        public ActionResult Cantidad()
        {
            
            return View();
        }

        public ActionResult guardaring(List<int>ID,List<int>Cantidad)
        {

            for (int i = 0; i < Cantidad.Count; i++)
            {
                if (Cantidad[i]>0)
                {
                    platillobo.ID = int.Parse(Session["IDPLATILLO"].ToString());
                    platillobo.IDINGREDIENTE = ID[i];
                    platillobo.cantidad = Cantidad[i];
                    ObjModel.Agregarcantidad(platillobo);
                }
            }
           
            Platillo(platillobo.ID);
            return View("Platillo");

        }

        public ActionResult VotacionPlatillo()
        {

            return View(ObjModel.PlatilloTemporal().Tables[0]);
        }

        public ActionResult AgregarVotacion(string Nombre, string TiempoPreparacion, HttpPostedFileBase Portada, string IDC, string Precio, string Descrip)
        {
            VotacionBo ObjBO = new VotacionBo();
            CategoriaBO objC = new CategoriaBO();
            Galeria obJGa = new Galeria();
            ObjBO.Nombre = Nombre;

            ObjBO.FechaCreacion = DateTime.Now;

            ObjBO.Preparacion = TiempoPreparacion;


            ObjBO.Estado = false;
            if (Portada != null && Portada.ContentLength > 0)
            {
                string imgfile = Portada.FileName;
                ObjBO.Portada = new byte[Portada.ContentLength];
                Portada.InputStream.Read(ObjBO.Portada, 0, Portada.ContentLength);
            }
            ObjBO.Precio = Precio;
            ObjBO.Descripcion = Descrip;
            ObjBO.IDCategoria = int.Parse(IDC);

            ObjBO.IDusuario = int.Parse(Session["Usuario"].ToString());
            ObjModel.AgregarPlatilloTem(ObjBO);

            return RedirectToAction("VotacionPlatillo");
        }

        public ActionResult CambiarEstatus(int id)
        {
            VotacionBo objbo = new VotacionBo();
            objbo.Estado = true;
            objbo.ID = id;
            ObjModel.ActualizarEstatus(objbo);
            return RedirectToAction("VotacionPlatillo");
        }


        public ActionResult VotacionActualizar(string Nombre, string TiempoPreparacion, HttpPostedFileBase Portada, string IDC, string Precio, string Descrip)
        {
            VotacionBo ObjBO = new VotacionBo();
            CategoriaBO objC = new CategoriaBO();
            Galeria obJGa = new Galeria();
            ObjBO.Nombre = Nombre;

            ObjBO.FechaCreacion = DateTime.Now;

            ObjBO.Preparacion = TiempoPreparacion;


            ObjBO.Estado = false;
            if (Portada != null && Portada.ContentLength > 0)
            {
                string imgfile = Portada.FileName;
                ObjBO.Portada = new byte[Portada.ContentLength];
                Portada.InputStream.Read(ObjBO.Portada, 0, Portada.ContentLength);
            }
            ObjBO.Precio = Precio;
            ObjBO.Descripcion = Descrip;
            ObjBO.IDCategoria = int.Parse(IDC);

            ObjBO.IDusuario = int.Parse(Session["Usuario"].ToString());
            ObjModel.ActualizarVotacion(ObjBO);

            return RedirectToAction("VotacionPlatillo");
        }
    }
}

Cocina-Tech/Views/Administrador/Cantidad.cshtml
@using System.Data
@model DataTable 
        
    
     
            
            @using (Html.BeginForm("guardaring", "Administrador", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {


                    <div class="content">

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Cantidad</label>
                                    <input type="text" class="form-control" placeholder="Cantidad" name="Cantidad">
                                </div>
                            </div>
                            @*<div class="row">
                                <div class="col-md-2">
                                    <input id="Button1" type="submit" value="Agregar Ingrediente" class="btn btn-info btn-fill pull-right" />
                                </div>
                            </div>*@
                            </div>
                        </div>
                        
            }
             
  
               
            
            

Cocina-Tech/Views/Administrador/Ingredientes.cshtml
@using System.Data;
@model DataTable


@using (Ajax.BeginForm("guardaring", "Administrador", new AjaxOptions() { HttpMethod = "POST" }))
{
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">INGREDIENTES</h4>
                        </div>
                        <div class="content">
                            <form>
                                <div class="row">
                                    <div class="clearfix"></div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="panel panel-default">

                                                <div class="panel-body panel-body-table">
                                                    <div class="table-responsive">
                                                        <table class="table table-bordered table-striped table-actions">
                                                            <thead>
                                                                <tr>
                                                                    <th width="50">ID</th>
                                                                    <th>Codigo</th>
                                                                    <th>Nombre</th>
                                                                    <th width="100">ESTADO</th>
                                                                    <th>MEDIDA</th>
                                                                    <th>FECHA</th>
                                                                    <th>CANTIDAD</th>
                                                                    <th width="100">ACCION</th>
                                                                </tr>
                                                            </thead>

                                                            
                                                           
                                                            @foreach (DataRow row in Model.Rows)
                                                            {
                                                                var algo = Model.Rows.Count;

                                                                <tbody>


                                                                    <tr id="trow_1">
                                                                        <td class="text-center">@row["ID"]</td>
                                                                        <td>
                                                                            <div class="form-group">
                                                                                <input type="text" class="form-control" placeholder="ID" name="ID" value=@row["ID"]>
                                                                            </div>
                                                                        </td>
                                                                        <td><strong>@row["NOMBRE"]</strong></td>
                                                                        <td><span class="label label-success">@row["Estado"]</span></td>
                                                                        <td>@row["MEDIDA"]</td>
                                                                        <td>@row["FECHACREACION"]</td>
                                                                        <td>
                                                                            <div class="form-group">
                                                                                <input type="text" class="form-control" placeholder="Cantidad" name="Cantidad">
                                                                            </div>
                                                                        </td>
                                                                        
                                                                        <td><button id="Button1" type="submit" class="btn btn-info btn-fill pull-right">Agregar ingredientes</button></td>

                                                                        

                                                                </tbody>
                                                            }
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>

                                                }

Cocina-Tech/Views/Administrador/Ingredientexplatillo.cshtml
@using System.Data
@model DataTable

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">

            <div class="panel-body panel-body-table">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-actions">
                        <thead>
                            <tr>
                                <th>Cantidad</th>
                                <th>Ingrediente</th>

                            </tr>
                        </thead>
                        @foreach (DataRow row in Model.Rows)
                        {

                            <tbody>


                                <tr id="trow_1">
                                    <td><strong>@row["CANTIDAD"]</strong></td>
                                    <td>@row["NOMBRE"]</td>

                            </tbody>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Cocina-Tech/Views/Administrador/Platillo.cshtml
@using System.Data
@model DataTable

@{
    ViewBag.Title = "Platillo";
    Layout = "~/Views/Administrador/Administrador.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">

            <div class="panel-body panel-body-table">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-actions">
                        <thead>
                            <tr>
                                <th width="50">ID</th>
                                <th>NOMBRE Platillo</th>
                                <th width="100">TIEMPO DE PREPARACION</th>
                                <th width="100">FECHA DE CREACION</th>
                                <th width="100">PRECIO</th>
                                <th width="100">ESTADO</th>
                            </tr>
                        </thead>
                        @foreach (DataRow row in Model.Rows)
                        {

                            <tbody>


                                <tr id="trow_1">
                                    <td class="text-center">@row["ID"]</td>
                                    <td><strong>@row["NOMBRE"]</strong></td>
                                    <td>@row["TIEMPODEPREPARACION"]</td>
                                    <td><strong>@row["FECHACREACIONPLATILLO"]</strong></td>
                                    <td><strong>@row["PRECIO"]</strong></td>
                                    <td><span class="label label-success">@row["ESTADO"]</span></td>
                                   
                            </tbody>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    @{ Html.RenderAction("Ingredientexplatillo", "Administrador");}
</div>
<div>
    @{ Html.RenderAction("Ingredientes", "Administrador");}
</div>

Cocina-Tech/Views/Administrador/Platillopingrediente.cshtml
@using System.Data
@model DataTable

@{
    ViewBag.Title = "Platillo Ingrediente";
    Layout = "~/Views/Administrador/Administrador.cshtml";
}



<div class="row">
    
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">Platillo Ingrediente</h4>
            </div>
            <div class="content">
               
                <div class="panel-body panel-body-table">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-actions">
                            <thead>
                                <tr>
                                    <th width="50">ID</th>
                                    <th>NOMBRE Platillo</th>
                                    <th width="100">TIEMPO DE PREPARACION</th>
                                    <th width="100">FECHA DE CREACION</th>
                                    <th width="100">ESTADO</th>
                                    <th width="100">PRECIO</th>
                                    <th width="100">ACCION</th>
                                </tr>
                            </thead>
                            @foreach (DataRow row in Model.Rows)
                    {

                        <tbody>


                            <tr id="trow_1">
                                <td class="text-center">@row["ID"]</td>
                                <td><strong>@row["NOMBRE"]</strong></td>
                                <td>@row["TIEMPODEPREPARACION"]</td>
                                <td><strong>@row["FECHACREACIONPLATILLO"]</strong></td>
                                <td><span class="label label-success">@(row["ESTADO"].ToString()=="True" ? "Disponible" : "No Disponible")</span></td>
                                <td><strong>@row["PRECIO"]</strong></td>
                                <td class="view-message" onclick="location.href='@($"/Administrador/Platillo/{@row["ID"]}")'"> Agregar ingredientes</td>


                        </tbody>
            }
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Cocina-Tech/Views/Administrador/VotacionPlatillo.cshtml
@using System.Data;
@model DataTable

@{
    ViewBag.Title = "RegistroUsuarios";
    Layout = "~/Views/Administrador/Administrador.cshtml";
}


<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <div class="card">
                    <div class="header">
                        <h4 class="title">REGISTRO VOTACION</h4>
                    </div>
                    <div class="content">
                        @using (Html.BeginForm("AgregarVotacion", "Administrador", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <form>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Nombre</label>
                                            <input type="text" class="form-control" placeholder="Nombre" name="Nombre">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Tiempo de Preparacion</label>
                                            <input type="text" class="form-control" placeholder="Tiempo De Preparacion" name="TiempoPreparacion">
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Precio</label>
                                        <input type="text" class="form-control" placeholder="Precio" name="Precio">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @{
                                            Html.RenderAction("ParcialPlatillo", "RegistroPlatillo");
                                        }
                                    </div>
                                </div>

                                <div class="row">

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Descripcion de Platillo</label>
                                            <input type="text" class="form-control" placeholder="Descripcion" name="Descrip">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Foto De Portada</label>
                                            <input id="File1" type="file" name="Portada" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-1">
                                    <button type="submit" class="btn btn-info btn-fill pull-right">Guardar</button>
                                </div>
                                <div class="clearfix"></div>
                            </form>
                                            }
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default">

                                <div class="panel-body panel-body-table">
                                    <div class="table-responsive">
                                        <table class="table table-bordered table-striped table-actions">
                                            <thead>
                                                <tr>

                                                    <th>NOMBRE</th>
                                                    <th width="100">FECHA DE CREACION</th>
                                                    <th width="100">DESCRIPCION</th>
                                                    <th width="100">TIEMPO DE PREPARACION</th>
                                                    <th width="100">ESTADO</th>
                                                    <th width="100">NUMERO DE VOTOS</th>
                                                    <th width="100">ACCION</th>

                                                </tr>
                                            </thead>
                                            @foreach (DataRow row in Model.Rows)
                                            {
                                                <tbody>


                                                    <tr>

                                                        <td><strong>@row["NOMBRE"]</strong></td>
                                                        <td><strong>@row["FECHACREACION"]</strong></td>
                                                        <td><strong>@row["DESCRIPCION"]</strong></td>
                                                        <td><strong>@row["TIEMPODEPREPARACION"]</strong></td>
                                                        <td><span class="label label-success">@row["ESTADO"]</span></td>
                                                        <td><strong>@row["NumeroVotos"]</strong></td>

                                                        <td>

                                                            @*<button class="btn btn-default btn-rounded btn-sm" href="~/Administrador/VotacionActualizar">
                                                                <a href="~/Administrador/VotacionActualizar"></a></abr><span class="fa fa-pencil" href="~/Administrador/VotacionActualizar"></span></button>*@


                                                            <span class="fa fa-times">
                                                                @*@Html.ActionLink("Eliminar", "Eliminarcat", "RegistroPlatillo", new { ID = row["ID"] })*@
                                                            </span>

                                                        </td>

                                                </tbody>}


                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>



                </div>
            </div>
        </div>

    </div>
</div>

Cocina-Tech/Views/Administrador/guardaring.cshtml
@{
    ViewBag.Title = "guardaring";
    Layout = "~/Views/Administrador/Administrador.cshtml";
}

<h2>guardaring</h2>